language: scala

scala:
  - 2.11.12
  - 2.12.6
  - 2.13.0-M4

jdk:
  - oraclejdk8

sudo: required
dist: trusty

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.coursier
    - $HOME/.sbt

env:
  global:
    - COURSIER_PROGRESS=0

script:
  - sbt ++$TRAVIS_SCALA_VERSION test doc mimaReportBinaryIssues

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -exec rm {} +
  - find $HOME/.ivy2 -name "ivydata-*.properties" -exec rm {} +

