addSbtPlugin("org.typelevel" % "sbt-typelevel" % "0.4.6")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.9.0")
addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler" % "0.20.0")
addSbtPlugin("com.github.tkawachi" % "sbt-doctest" % "0.9.9")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.3.0")
